engines:
  eslint:
    enabled: true
    channel: "eslint-7"
    config: .eslintrc.json
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.scss"

exclude_paths:
- static/**/*
- content/**/*
- cypress/**/*
- gatsby-config.mjs
- gatsby-node.mjs
